name: vyv
description: Vyv app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: any
  get: 4.5.1
  get_storage: ^2.0.3
  flutter_svg: ^0.22.0
  gestures: ^1.0.0
  percent_indicator: ^4.0.0
  google_maps_flutter: ^2.0.9
  url_launcher: ^6.0.10
  lazy_load_scrollview: ^1.3.0
  pagination_view: ^2.0.0
  intl: ^0.17.0
  infinite_scroll_pagination: ^3.1.0
  geolocator: ^8.0.5
  geocoding: ^2.0.4
  share_plus: ^3.0.1
  cell_calendar: ^0.5.0+1
  permission_handler: ^8.1.6

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/images/svgs/

  fonts:
    - family: GemunuLibre
      fonts:
        - asset: assets/fonts/GemunuLibre/GemunuLibre-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/GemunuLibre/GemunuLibre-Light.ttf
          weight: 300
        - asset: assets/fonts/GemunuLibre/GemunuLibre-Regular.ttf
          weight: 400
        - asset: assets/fonts/GemunuLibre/GemunuLibre-Medium.ttf
          weight: 500
        - asset: assets/fonts/GemunuLibre/GemunuLibre-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/GemunuLibre/GemunuLibre-Bold.ttf
          weight: 700
        - asset: assets/fonts/GemunuLibre/GemunuLibre-ExtraBold.ttf
          weight: 800
    - family: Heebo
      fonts:
        - asset: assets/fonts/heebo/Heebo-Thin.ttf
          weight: 100
        #        - asset: assets/fonts/heebo/Heebo-ExtraLight.ttf
        #          weight: 200
        - asset: assets/fonts/heebo/Heebo-Light.ttf
          weight: 300
        - asset: assets/fonts/heebo/Heebo-Regular.ttf
          weight: 400
        - asset: assets/fonts/heebo/Heebo-Medium.ttf
          weight: 500
        #        - asset: assets/fonts/Heebo/Heebo-SemiBold.ttf
        #          weight: 600
        - asset: assets/fonts/heebo/Heebo-Bold.ttf
          weight: 700
        - asset: assets/fonts/heebo/Heebo-ExtraBold.ttf
          weight: 800